server:
    port: 8080
spring:
    application:
        name: 'idm project'

video:
    pathVideo:
        original: 'src/main/resources/static/video/original'
        generated: 'src/main/resources/static/video/generated'