version: '2'
services:
    videogen-app:
        image: videogen
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://videogen-mysql:3306/videogen?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    videogen-mysql:
        extends:
            file: mysql.yml
            service: videogen-mysql
