/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.videoGen;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Alternatives Media</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.videoGen.AlternativesMedia#getId <em>Id</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.videoGen.AlternativesMedia#getMedias <em>Medias</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.videoGen.VideoGenPackage#getAlternativesMedia()
 * @model
 * @generated
 */
public interface AlternativesMedia extends Media
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.xtext.example.mydsl.videoGen.VideoGenPackage#getAlternativesMedia_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.videoGen.AlternativesMedia#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Medias</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.videoGen.MediaDescription}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Medias</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Medias</em>' containment reference list.
   * @see org.xtext.example.mydsl.videoGen.VideoGenPackage#getAlternativesMedia_Medias()
   * @model containment="true"
   * @generated
   */
  EList<MediaDescription> getMedias();

} // AlternativesMedia
