/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.videoGen;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.videoGen.VideoGenFactory
 * @model kind="package"
 * @generated
 */
public interface VideoGenPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "videoGen";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/VideoGen";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "videoGen";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VideoGenPackage eINSTANCE = org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.videoGen.impl.VideoGeneratorModelImpl <em>Video Generator Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.videoGen.impl.VideoGeneratorModelImpl
   * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getVideoGeneratorModel()
   * @generated
   */
  int VIDEO_GENERATOR_MODEL = 0;

  /**
   * The feature id for the '<em><b>Information</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_GENERATOR_MODEL__INFORMATION = 0;

  /**
   * The feature id for the '<em><b>Medias</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_GENERATOR_MODEL__MEDIAS = 1;

  /**
   * The number of structural features of the '<em>Video Generator Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_GENERATOR_MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.videoGen.impl.VideoGenInformationImpl <em>Information</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.videoGen.impl.VideoGenInformationImpl
   * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getVideoGenInformation()
   * @generated
   */
  int VIDEO_GEN_INFORMATION = 1;

  /**
   * The feature id for the '<em><b>Author Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_GEN_INFORMATION__AUTHOR_NAME = 0;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_GEN_INFORMATION__VERSION = 1;

  /**
   * The feature id for the '<em><b>Creation Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_GEN_INFORMATION__CREATION_DATE = 2;

  /**
   * The number of structural features of the '<em>Information</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_GEN_INFORMATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.videoGen.impl.MediaImpl <em>Media</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.videoGen.impl.MediaImpl
   * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getMedia()
   * @generated
   */
  int MEDIA = 2;

  /**
   * The number of structural features of the '<em>Media</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDIA_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.videoGen.impl.MandatoryMediaImpl <em>Mandatory Media</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.videoGen.impl.MandatoryMediaImpl
   * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getMandatoryMedia()
   * @generated
   */
  int MANDATORY_MEDIA = 3;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANDATORY_MEDIA__DESCRIPTION = MEDIA_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Mandatory Media</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANDATORY_MEDIA_FEATURE_COUNT = MEDIA_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.videoGen.impl.OptionalMediaImpl <em>Optional Media</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.videoGen.impl.OptionalMediaImpl
   * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getOptionalMedia()
   * @generated
   */
  int OPTIONAL_MEDIA = 4;

  /**
   * The feature id for the '<em><b>Description</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTIONAL_MEDIA__DESCRIPTION = MEDIA_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Optional Media</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPTIONAL_MEDIA_FEATURE_COUNT = MEDIA_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.videoGen.impl.AlternativesMediaImpl <em>Alternatives Media</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.videoGen.impl.AlternativesMediaImpl
   * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getAlternativesMedia()
   * @generated
   */
  int ALTERNATIVES_MEDIA = 5;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALTERNATIVES_MEDIA__ID = MEDIA_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Medias</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALTERNATIVES_MEDIA__MEDIAS = MEDIA_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Alternatives Media</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALTERNATIVES_MEDIA_FEATURE_COUNT = MEDIA_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.videoGen.impl.MediaDescriptionImpl <em>Media Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.videoGen.impl.MediaDescriptionImpl
   * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getMediaDescription()
   * @generated
   */
  int MEDIA_DESCRIPTION = 6;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDIA_DESCRIPTION__LOCATION = 0;

  /**
   * The number of structural features of the '<em>Media Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MEDIA_DESCRIPTION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.videoGen.impl.ImageDescriptionImpl <em>Image Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.videoGen.impl.ImageDescriptionImpl
   * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getImageDescription()
   * @generated
   */
  int IMAGE_DESCRIPTION = 7;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_DESCRIPTION__LOCATION = MEDIA_DESCRIPTION__LOCATION;

  /**
   * The feature id for the '<em><b>Imageid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_DESCRIPTION__IMAGEID = MEDIA_DESCRIPTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Top</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_DESCRIPTION__TOP = MEDIA_DESCRIPTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Bottom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_DESCRIPTION__BOTTOM = MEDIA_DESCRIPTION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Image Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMAGE_DESCRIPTION_FEATURE_COUNT = MEDIA_DESCRIPTION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.videoGen.impl.VideoDescriptionImpl <em>Video Description</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.videoGen.impl.VideoDescriptionImpl
   * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getVideoDescription()
   * @generated
   */
  int VIDEO_DESCRIPTION = 8;

  /**
   * The feature id for the '<em><b>Location</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_DESCRIPTION__LOCATION = MEDIA_DESCRIPTION__LOCATION;

  /**
   * The feature id for the '<em><b>Videoid</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_DESCRIPTION__VIDEOID = MEDIA_DESCRIPTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_DESCRIPTION__DURATION = MEDIA_DESCRIPTION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Probability</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_DESCRIPTION__PROBABILITY = MEDIA_DESCRIPTION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_DESCRIPTION__DESCRIPTION = MEDIA_DESCRIPTION_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Filter</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_DESCRIPTION__FILTER = MEDIA_DESCRIPTION_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_DESCRIPTION__TEXT = MEDIA_DESCRIPTION_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Video Description</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_DESCRIPTION_FEATURE_COUNT = MEDIA_DESCRIPTION_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.videoGen.impl.VideoTextImpl <em>Video Text</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.videoGen.impl.VideoTextImpl
   * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getVideoText()
   * @generated
   */
  int VIDEO_TEXT = 9;

  /**
   * The feature id for the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_TEXT__CONTENT = 0;

  /**
   * The feature id for the '<em><b>Position</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_TEXT__POSITION = 1;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_TEXT__COLOR = 2;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_TEXT__SIZE = 3;

  /**
   * The number of structural features of the '<em>Video Text</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VIDEO_TEXT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.videoGen.impl.FilterImpl <em>Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.videoGen.impl.FilterImpl
   * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getFilter()
   * @generated
   */
  int FILTER = 10;

  /**
   * The number of structural features of the '<em>Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.videoGen.impl.BlackWhiteFilterImpl <em>Black White Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.videoGen.impl.BlackWhiteFilterImpl
   * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getBlackWhiteFilter()
   * @generated
   */
  int BLACK_WHITE_FILTER = 11;

  /**
   * The number of structural features of the '<em>Black White Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLACK_WHITE_FILTER_FEATURE_COUNT = FILTER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.videoGen.impl.NegateFilterImpl <em>Negate Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.videoGen.impl.NegateFilterImpl
   * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getNegateFilter()
   * @generated
   */
  int NEGATE_FILTER = 12;

  /**
   * The number of structural features of the '<em>Negate Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NEGATE_FILTER_FEATURE_COUNT = FILTER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.videoGen.impl.FlipFilterImpl <em>Flip Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.videoGen.impl.FlipFilterImpl
   * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getFlipFilter()
   * @generated
   */
  int FLIP_FILTER = 13;

  /**
   * The feature id for the '<em><b>Orientation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIP_FILTER__ORIENTATION = FILTER_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Flip Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLIP_FILTER_FEATURE_COUNT = FILTER_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.videoGen.VideoGeneratorModel <em>Video Generator Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Video Generator Model</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoGeneratorModel
   * @generated
   */
  EClass getVideoGeneratorModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.videoGen.VideoGeneratorModel#getInformation <em>Information</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Information</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoGeneratorModel#getInformation()
   * @see #getVideoGeneratorModel()
   * @generated
   */
  EReference getVideoGeneratorModel_Information();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.videoGen.VideoGeneratorModel#getMedias <em>Medias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Medias</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoGeneratorModel#getMedias()
   * @see #getVideoGeneratorModel()
   * @generated
   */
  EReference getVideoGeneratorModel_Medias();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.videoGen.VideoGenInformation <em>Information</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Information</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoGenInformation
   * @generated
   */
  EClass getVideoGenInformation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.videoGen.VideoGenInformation#getAuthorName <em>Author Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Author Name</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoGenInformation#getAuthorName()
   * @see #getVideoGenInformation()
   * @generated
   */
  EAttribute getVideoGenInformation_AuthorName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.videoGen.VideoGenInformation#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoGenInformation#getVersion()
   * @see #getVideoGenInformation()
   * @generated
   */
  EAttribute getVideoGenInformation_Version();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.videoGen.VideoGenInformation#getCreationDate <em>Creation Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Creation Date</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoGenInformation#getCreationDate()
   * @see #getVideoGenInformation()
   * @generated
   */
  EAttribute getVideoGenInformation_CreationDate();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.videoGen.Media <em>Media</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Media</em>'.
   * @see org.xtext.example.mydsl.videoGen.Media
   * @generated
   */
  EClass getMedia();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.videoGen.MandatoryMedia <em>Mandatory Media</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mandatory Media</em>'.
   * @see org.xtext.example.mydsl.videoGen.MandatoryMedia
   * @generated
   */
  EClass getMandatoryMedia();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.videoGen.MandatoryMedia#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.xtext.example.mydsl.videoGen.MandatoryMedia#getDescription()
   * @see #getMandatoryMedia()
   * @generated
   */
  EReference getMandatoryMedia_Description();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.videoGen.OptionalMedia <em>Optional Media</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Optional Media</em>'.
   * @see org.xtext.example.mydsl.videoGen.OptionalMedia
   * @generated
   */
  EClass getOptionalMedia();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.videoGen.OptionalMedia#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Description</em>'.
   * @see org.xtext.example.mydsl.videoGen.OptionalMedia#getDescription()
   * @see #getOptionalMedia()
   * @generated
   */
  EReference getOptionalMedia_Description();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.videoGen.AlternativesMedia <em>Alternatives Media</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Alternatives Media</em>'.
   * @see org.xtext.example.mydsl.videoGen.AlternativesMedia
   * @generated
   */
  EClass getAlternativesMedia();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.videoGen.AlternativesMedia#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see org.xtext.example.mydsl.videoGen.AlternativesMedia#getId()
   * @see #getAlternativesMedia()
   * @generated
   */
  EAttribute getAlternativesMedia_Id();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.videoGen.AlternativesMedia#getMedias <em>Medias</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Medias</em>'.
   * @see org.xtext.example.mydsl.videoGen.AlternativesMedia#getMedias()
   * @see #getAlternativesMedia()
   * @generated
   */
  EReference getAlternativesMedia_Medias();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.videoGen.MediaDescription <em>Media Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Media Description</em>'.
   * @see org.xtext.example.mydsl.videoGen.MediaDescription
   * @generated
   */
  EClass getMediaDescription();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.videoGen.MediaDescription#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Location</em>'.
   * @see org.xtext.example.mydsl.videoGen.MediaDescription#getLocation()
   * @see #getMediaDescription()
   * @generated
   */
  EAttribute getMediaDescription_Location();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.videoGen.ImageDescription <em>Image Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Image Description</em>'.
   * @see org.xtext.example.mydsl.videoGen.ImageDescription
   * @generated
   */
  EClass getImageDescription();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.videoGen.ImageDescription#getImageid <em>Imageid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imageid</em>'.
   * @see org.xtext.example.mydsl.videoGen.ImageDescription#getImageid()
   * @see #getImageDescription()
   * @generated
   */
  EAttribute getImageDescription_Imageid();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.videoGen.ImageDescription#getTop <em>Top</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Top</em>'.
   * @see org.xtext.example.mydsl.videoGen.ImageDescription#getTop()
   * @see #getImageDescription()
   * @generated
   */
  EAttribute getImageDescription_Top();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.videoGen.ImageDescription#getBottom <em>Bottom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bottom</em>'.
   * @see org.xtext.example.mydsl.videoGen.ImageDescription#getBottom()
   * @see #getImageDescription()
   * @generated
   */
  EAttribute getImageDescription_Bottom();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.videoGen.VideoDescription <em>Video Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Video Description</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoDescription
   * @generated
   */
  EClass getVideoDescription();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.videoGen.VideoDescription#getVideoid <em>Videoid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Videoid</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoDescription#getVideoid()
   * @see #getVideoDescription()
   * @generated
   */
  EAttribute getVideoDescription_Videoid();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.videoGen.VideoDescription#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoDescription#getDuration()
   * @see #getVideoDescription()
   * @generated
   */
  EAttribute getVideoDescription_Duration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.videoGen.VideoDescription#getProbability <em>Probability</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Probability</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoDescription#getProbability()
   * @see #getVideoDescription()
   * @generated
   */
  EAttribute getVideoDescription_Probability();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.videoGen.VideoDescription#getDescription <em>Description</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Description</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoDescription#getDescription()
   * @see #getVideoDescription()
   * @generated
   */
  EAttribute getVideoDescription_Description();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.videoGen.VideoDescription#getFilter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Filter</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoDescription#getFilter()
   * @see #getVideoDescription()
   * @generated
   */
  EReference getVideoDescription_Filter();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.videoGen.VideoDescription#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoDescription#getText()
   * @see #getVideoDescription()
   * @generated
   */
  EReference getVideoDescription_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.videoGen.VideoText <em>Video Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Video Text</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoText
   * @generated
   */
  EClass getVideoText();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.videoGen.VideoText#getContent <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Content</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoText#getContent()
   * @see #getVideoText()
   * @generated
   */
  EAttribute getVideoText_Content();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.videoGen.VideoText#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Position</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoText#getPosition()
   * @see #getVideoText()
   * @generated
   */
  EAttribute getVideoText_Position();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.videoGen.VideoText#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoText#getColor()
   * @see #getVideoText()
   * @generated
   */
  EAttribute getVideoText_Color();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.videoGen.VideoText#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size</em>'.
   * @see org.xtext.example.mydsl.videoGen.VideoText#getSize()
   * @see #getVideoText()
   * @generated
   */
  EAttribute getVideoText_Size();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.videoGen.Filter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter</em>'.
   * @see org.xtext.example.mydsl.videoGen.Filter
   * @generated
   */
  EClass getFilter();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.videoGen.BlackWhiteFilter <em>Black White Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Black White Filter</em>'.
   * @see org.xtext.example.mydsl.videoGen.BlackWhiteFilter
   * @generated
   */
  EClass getBlackWhiteFilter();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.videoGen.NegateFilter <em>Negate Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Negate Filter</em>'.
   * @see org.xtext.example.mydsl.videoGen.NegateFilter
   * @generated
   */
  EClass getNegateFilter();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.videoGen.FlipFilter <em>Flip Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Flip Filter</em>'.
   * @see org.xtext.example.mydsl.videoGen.FlipFilter
   * @generated
   */
  EClass getFlipFilter();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.videoGen.FlipFilter#getOrientation <em>Orientation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Orientation</em>'.
   * @see org.xtext.example.mydsl.videoGen.FlipFilter#getOrientation()
   * @see #getFlipFilter()
   * @generated
   */
  EAttribute getFlipFilter_Orientation();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  VideoGenFactory getVideoGenFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.videoGen.impl.VideoGeneratorModelImpl <em>Video Generator Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.videoGen.impl.VideoGeneratorModelImpl
     * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getVideoGeneratorModel()
     * @generated
     */
    EClass VIDEO_GENERATOR_MODEL = eINSTANCE.getVideoGeneratorModel();

    /**
     * The meta object literal for the '<em><b>Information</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VIDEO_GENERATOR_MODEL__INFORMATION = eINSTANCE.getVideoGeneratorModel_Information();

    /**
     * The meta object literal for the '<em><b>Medias</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VIDEO_GENERATOR_MODEL__MEDIAS = eINSTANCE.getVideoGeneratorModel_Medias();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.videoGen.impl.VideoGenInformationImpl <em>Information</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.videoGen.impl.VideoGenInformationImpl
     * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getVideoGenInformation()
     * @generated
     */
    EClass VIDEO_GEN_INFORMATION = eINSTANCE.getVideoGenInformation();

    /**
     * The meta object literal for the '<em><b>Author Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_GEN_INFORMATION__AUTHOR_NAME = eINSTANCE.getVideoGenInformation_AuthorName();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_GEN_INFORMATION__VERSION = eINSTANCE.getVideoGenInformation_Version();

    /**
     * The meta object literal for the '<em><b>Creation Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_GEN_INFORMATION__CREATION_DATE = eINSTANCE.getVideoGenInformation_CreationDate();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.videoGen.impl.MediaImpl <em>Media</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.videoGen.impl.MediaImpl
     * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getMedia()
     * @generated
     */
    EClass MEDIA = eINSTANCE.getMedia();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.videoGen.impl.MandatoryMediaImpl <em>Mandatory Media</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.videoGen.impl.MandatoryMediaImpl
     * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getMandatoryMedia()
     * @generated
     */
    EClass MANDATORY_MEDIA = eINSTANCE.getMandatoryMedia();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MANDATORY_MEDIA__DESCRIPTION = eINSTANCE.getMandatoryMedia_Description();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.videoGen.impl.OptionalMediaImpl <em>Optional Media</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.videoGen.impl.OptionalMediaImpl
     * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getOptionalMedia()
     * @generated
     */
    EClass OPTIONAL_MEDIA = eINSTANCE.getOptionalMedia();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OPTIONAL_MEDIA__DESCRIPTION = eINSTANCE.getOptionalMedia_Description();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.videoGen.impl.AlternativesMediaImpl <em>Alternatives Media</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.videoGen.impl.AlternativesMediaImpl
     * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getAlternativesMedia()
     * @generated
     */
    EClass ALTERNATIVES_MEDIA = eINSTANCE.getAlternativesMedia();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALTERNATIVES_MEDIA__ID = eINSTANCE.getAlternativesMedia_Id();

    /**
     * The meta object literal for the '<em><b>Medias</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALTERNATIVES_MEDIA__MEDIAS = eINSTANCE.getAlternativesMedia_Medias();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.videoGen.impl.MediaDescriptionImpl <em>Media Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.videoGen.impl.MediaDescriptionImpl
     * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getMediaDescription()
     * @generated
     */
    EClass MEDIA_DESCRIPTION = eINSTANCE.getMediaDescription();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MEDIA_DESCRIPTION__LOCATION = eINSTANCE.getMediaDescription_Location();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.videoGen.impl.ImageDescriptionImpl <em>Image Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.videoGen.impl.ImageDescriptionImpl
     * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getImageDescription()
     * @generated
     */
    EClass IMAGE_DESCRIPTION = eINSTANCE.getImageDescription();

    /**
     * The meta object literal for the '<em><b>Imageid</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGE_DESCRIPTION__IMAGEID = eINSTANCE.getImageDescription_Imageid();

    /**
     * The meta object literal for the '<em><b>Top</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGE_DESCRIPTION__TOP = eINSTANCE.getImageDescription_Top();

    /**
     * The meta object literal for the '<em><b>Bottom</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMAGE_DESCRIPTION__BOTTOM = eINSTANCE.getImageDescription_Bottom();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.videoGen.impl.VideoDescriptionImpl <em>Video Description</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.videoGen.impl.VideoDescriptionImpl
     * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getVideoDescription()
     * @generated
     */
    EClass VIDEO_DESCRIPTION = eINSTANCE.getVideoDescription();

    /**
     * The meta object literal for the '<em><b>Videoid</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_DESCRIPTION__VIDEOID = eINSTANCE.getVideoDescription_Videoid();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_DESCRIPTION__DURATION = eINSTANCE.getVideoDescription_Duration();

    /**
     * The meta object literal for the '<em><b>Probability</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_DESCRIPTION__PROBABILITY = eINSTANCE.getVideoDescription_Probability();

    /**
     * The meta object literal for the '<em><b>Description</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_DESCRIPTION__DESCRIPTION = eINSTANCE.getVideoDescription_Description();

    /**
     * The meta object literal for the '<em><b>Filter</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VIDEO_DESCRIPTION__FILTER = eINSTANCE.getVideoDescription_Filter();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VIDEO_DESCRIPTION__TEXT = eINSTANCE.getVideoDescription_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.videoGen.impl.VideoTextImpl <em>Video Text</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.videoGen.impl.VideoTextImpl
     * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getVideoText()
     * @generated
     */
    EClass VIDEO_TEXT = eINSTANCE.getVideoText();

    /**
     * The meta object literal for the '<em><b>Content</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_TEXT__CONTENT = eINSTANCE.getVideoText_Content();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_TEXT__POSITION = eINSTANCE.getVideoText_Position();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_TEXT__COLOR = eINSTANCE.getVideoText_Color();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VIDEO_TEXT__SIZE = eINSTANCE.getVideoText_Size();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.videoGen.impl.FilterImpl <em>Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.videoGen.impl.FilterImpl
     * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getFilter()
     * @generated
     */
    EClass FILTER = eINSTANCE.getFilter();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.videoGen.impl.BlackWhiteFilterImpl <em>Black White Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.videoGen.impl.BlackWhiteFilterImpl
     * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getBlackWhiteFilter()
     * @generated
     */
    EClass BLACK_WHITE_FILTER = eINSTANCE.getBlackWhiteFilter();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.videoGen.impl.NegateFilterImpl <em>Negate Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.videoGen.impl.NegateFilterImpl
     * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getNegateFilter()
     * @generated
     */
    EClass NEGATE_FILTER = eINSTANCE.getNegateFilter();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.videoGen.impl.FlipFilterImpl <em>Flip Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.videoGen.impl.FlipFilterImpl
     * @see org.xtext.example.mydsl.videoGen.impl.VideoGenPackageImpl#getFlipFilter()
     * @generated
     */
    EClass FLIP_FILTER = eINSTANCE.getFlipFilter();

    /**
     * The meta object literal for the '<em><b>Orientation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLIP_FILTER__ORIENTATION = eINSTANCE.getFlipFilter_Orientation();

  }

} //VideoGenPackage
