/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.videoGen;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.videoGen.VideoGenPackage
 * @generated
 */
public interface VideoGenFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VideoGenFactory eINSTANCE = org.xtext.example.mydsl.videoGen.impl.VideoGenFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Video Generator Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Video Generator Model</em>'.
   * @generated
   */
  VideoGeneratorModel createVideoGeneratorModel();

  /**
   * Returns a new object of class '<em>Information</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Information</em>'.
   * @generated
   */
  VideoGenInformation createVideoGenInformation();

  /**
   * Returns a new object of class '<em>Media</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Media</em>'.
   * @generated
   */
  Media createMedia();

  /**
   * Returns a new object of class '<em>Mandatory Media</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Mandatory Media</em>'.
   * @generated
   */
  MandatoryMedia createMandatoryMedia();

  /**
   * Returns a new object of class '<em>Optional Media</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Optional Media</em>'.
   * @generated
   */
  OptionalMedia createOptionalMedia();

  /**
   * Returns a new object of class '<em>Alternatives Media</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Alternatives Media</em>'.
   * @generated
   */
  AlternativesMedia createAlternativesMedia();

  /**
   * Returns a new object of class '<em>Media Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Media Description</em>'.
   * @generated
   */
  MediaDescription createMediaDescription();

  /**
   * Returns a new object of class '<em>Image Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Image Description</em>'.
   * @generated
   */
  ImageDescription createImageDescription();

  /**
   * Returns a new object of class '<em>Video Description</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Video Description</em>'.
   * @generated
   */
  VideoDescription createVideoDescription();

  /**
   * Returns a new object of class '<em>Video Text</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Video Text</em>'.
   * @generated
   */
  VideoText createVideoText();

  /**
   * Returns a new object of class '<em>Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Filter</em>'.
   * @generated
   */
  Filter createFilter();

  /**
   * Returns a new object of class '<em>Black White Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Black White Filter</em>'.
   * @generated
   */
  BlackWhiteFilter createBlackWhiteFilter();

  /**
   * Returns a new object of class '<em>Negate Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Negate Filter</em>'.
   * @generated
   */
  NegateFilter createNegateFilter();

  /**
   * Returns a new object of class '<em>Flip Filter</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Flip Filter</em>'.
   * @generated
   */
  FlipFilter createFlipFilter();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  VideoGenPackage getVideoGenPackage();

} //VideoGenFactory
